# Generated by Django 4.2.7 on 2026-01-03 17:38

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0001_initial'),
        ('questions', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('attempt_number', models.PositiveIntegerField(default=1, verbose_name='答题次数')),
                ('status', models.CharField(choices=[('IN_PROGRESS', '答题中'), ('SUBMITTED', '已提交'), ('GRADING', '待评分'), ('GRADED', '已评分')], default='IN_PROGRESS', max_length=20, verbose_name='状态')),
                ('total_score', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='试卷总分')),
                ('obtained_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='获得分数')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('remaining_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='剩余时间（秒）')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='quizzes.quiz', verbose_name='试卷')),
                ('task_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tasks.taskassignment', verbose_name='任务分配')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='答题用户')),
            ],
            options={
                'verbose_name': '答题记录',
                'verbose_name_plural': '答题记录',
                'db_table': 'lms_submission',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user_answer', models.JSONField(blank=True, null=True, verbose_name='用户答案')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='是否正确')),
                ('obtained_score', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='得分')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='评分时间')),
                ('comment', models.TextField(blank=True, default='', verbose_name='评语')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_answers', to=settings.AUTH_USER_MODEL, verbose_name='评分人')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='questions.question', verbose_name='题目')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='submissions.submission', verbose_name='答题记录')),
            ],
            options={
                'verbose_name': '答案记录',
                'verbose_name_plural': '答案记录',
                'db_table': 'lms_answer',
                'ordering': ['submission', 'question'],
                'unique_together': {('submission', 'question')},
            },
        ),
    ]
