# Generated by Django 4.2.7 on 2026-04-20 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='task_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tasks.taskassignment', verbose_name='任务分配'),
        ),
        migrations.AddField(
            model_name='submission',
            name='task_quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='tasks.taskquiz', verbose_name='任务试卷'),
        ),
    ]
