# Generated by Django 4.2.7 on 2026-07-13 08:43
# 修正：启用约束前清 NULL、修/删关联不一致、去重并重排 attempt_number。

from django.db import migrations, models
import django.db.models.deletion


_STATUS_RANK = {
    'GRADED': 4,
    'GRADING': 3,
    'SUBMITTED': 2,
    'IN_PROGRESS': 1,
}

_TEMP_ATTEMPT_BASE = 1_000_000_000


def _rank_key(submission):
    return (
        _STATUS_RANK.get(submission.status, 0),
        submission.obtained_score if submission.obtained_score is not None else -1,
        submission.submitted_at is not None,
        submission.submitted_at or submission.created_at,
        submission.id,
    )


def _pick_best(submissions):
    return max(submissions, key=_rank_key)


def backfill_or_delete_null_task_quiz(apps, schema_editor):
    """补齐 task_quiz 为空的历史提交；键冲突时按状态优先级保留更完整的一条。"""
    Submission = apps.get_model('submissions', 'Submission')
    TaskAssignment = apps.get_model('tasks', 'TaskAssignment')
    TaskQuiz = apps.get_model('tasks', 'TaskQuiz')

    for submission in Submission.objects.filter(task_quiz_id__isnull=True).iterator():
        assignment = TaskAssignment.objects.filter(pk=submission.task_assignment_id).first()
        if assignment is None or not submission.quiz_id:
            submission.delete()
            continue

        matches = list(
            TaskQuiz.objects.filter(
                task_id=assignment.task_id,
                quiz_id=submission.quiz_id,
            ).order_by('id')[:2]
        )
        if len(matches) != 1:
            submission.delete()
            continue

        task_quiz = matches[0]
        conflicts = list(
            Submission.objects.filter(
                task_assignment_id=submission.task_assignment_id,
                task_quiz_id=task_quiz.id,
                attempt_number=submission.attempt_number,
            ).exclude(pk=submission.pk)
        )
        if conflicts:
            best = _pick_best(conflicts + [submission])
            if best.pk != submission.pk:
                # 已有记录更优：丢掉这条 NULL 答卷
                submission.delete()
                continue
            # 本条更优：删掉冲突行后再回填
            for other in conflicts:
                other.delete()

        submission.task_quiz_id = task_quiz.id
        submission.save(update_fields=['task_quiz_id'])


def fix_or_delete_inconsistent_submissions(apps, schema_editor):
    """修复或删除与模型 clean() 不一致的历史答卷，避免升级后 full_clean 全线失败。

    - user != assignee：改为被分配人
    - task_quiz 不属于 assignment.task / quiz 与 task_quiz 不一致 / 关联缺失：删除
    """
    Submission = apps.get_model('submissions', 'Submission')
    TaskAssignment = apps.get_model('tasks', 'TaskAssignment')
    TaskQuiz = apps.get_model('tasks', 'TaskQuiz')

    for submission in Submission.objects.all().iterator():
        assignment = TaskAssignment.objects.filter(pk=submission.task_assignment_id).first()
        if assignment is None:
            submission.delete()
            continue

        if not submission.task_quiz_id or not submission.quiz_id or not submission.user_id:
            submission.delete()
            continue

        task_quiz = TaskQuiz.objects.filter(pk=submission.task_quiz_id).first()
        if task_quiz is None:
            submission.delete()
            continue

        if task_quiz.task_id != assignment.task_id:
            submission.delete()
            continue

        if submission.quiz_id != task_quiz.quiz_id:
            # 答案挂在错误试卷快照上，无法安全纠偏
            submission.delete()
            continue

        if submission.user_id != assignment.assignee_id:
            submission.user_id = assignment.assignee_id
            submission.save(update_fields=['user_id'])


def delete_duplicate_submissions(apps, schema_editor):
    """删除 (task_assignment, task_quiz, attempt_number) 重复行，保留最优一条。"""
    Submission = apps.get_model('submissions', 'Submission')

    groups = {}
    for submission in Submission.objects.all().iterator():
        key = (
            submission.task_assignment_id,
            submission.task_quiz_id,
            submission.attempt_number,
        )
        groups.setdefault(key, []).append(submission)

    for submissions in groups.values():
        if len(submissions) <= 1:
            continue
        best = _pick_best(submissions)
        for duplicate in submissions:
            if duplicate.pk != best.pk:
                duplicate.delete()


def renumber_attempt_numbers(apps, schema_editor):
    """去重后按组把 attempt_number 压成 1..n，避免留下 1、3 空洞。"""
    Submission = apps.get_model('submissions', 'Submission')

    groups = {}
    for submission in Submission.objects.all().iterator():
        key = (submission.task_assignment_id, submission.task_quiz_id)
        groups.setdefault(key, []).append(submission)

    for submissions in groups.values():
        submissions.sort(key=lambda s: (s.attempt_number, s.created_at, s.id))
        if all(s.attempt_number == index for index, s in enumerate(submissions, start=1)):
            continue
        for offset, submission in enumerate(submissions):
            submission.attempt_number = _TEMP_ATTEMPT_BASE + offset
            submission.save(update_fields=['attempt_number'])
        for index, submission in enumerate(submissions, start=1):
            submission.attempt_number = index
            submission.save(update_fields=['attempt_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(backfill_or_delete_null_task_quiz, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='submission',
            name='task_quiz',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='submissions',
                to='tasks.taskquiz',
                verbose_name='任务试卷',
            ),
        ),
        migrations.RunPython(fix_or_delete_inconsistent_submissions, migrations.RunPython.noop),
        migrations.RunPython(delete_duplicate_submissions, migrations.RunPython.noop),
        migrations.RunPython(renumber_attempt_numbers, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(
                fields=('task_assignment', 'task_quiz', 'attempt_number'),
                name='uniq_submission_assignment_task_quiz_attempt',
            ),
        ),
    ]
