# Generated by Django 4.2.7 on 2026-07-13 08:43
# 修正：AddConstraint 前先清 NULL、收紧非空、去重并重排 attempt_number。

from django.db import migrations, models
import django.db.models.deletion


_STATUS_RANK = {
    'GRADED': 4,
    'GRADING': 3,
    'SUBMITTED': 2,
    'IN_PROGRESS': 1,
}

_TEMP_ATTEMPT_BASE = 1_000_000_000


def backfill_or_delete_null_task_quiz(apps, schema_editor):
    """补齐或删除 task_quiz 为空的历史提交。"""
    Submission = apps.get_model('submissions', 'Submission')
    TaskAssignment = apps.get_model('tasks', 'TaskAssignment')
    TaskQuiz = apps.get_model('tasks', 'TaskQuiz')

    for submission in Submission.objects.filter(task_quiz_id__isnull=True).iterator():
        assignment = TaskAssignment.objects.filter(pk=submission.task_assignment_id).first()
        if assignment is None or not submission.quiz_id:
            submission.delete()
            continue

        matches = list(
            TaskQuiz.objects.filter(
                task_id=assignment.task_id,
                quiz_id=submission.quiz_id,
            ).order_by('id')[:2]
        )
        if len(matches) != 1:
            submission.delete()
            continue

        task_quiz = matches[0]
        conflict = (
            Submission.objects.filter(
                task_assignment_id=submission.task_assignment_id,
                task_quiz_id=task_quiz.id,
                attempt_number=submission.attempt_number,
            )
            .exclude(pk=submission.pk)
            .exists()
        )
        if conflict:
            submission.delete()
            continue

        submission.task_quiz_id = task_quiz.id
        submission.save(update_fields=['task_quiz_id'])


def delete_duplicate_submissions(apps, schema_editor):
    """删除 (task_assignment, task_quiz, attempt_number) 重复行，保留最优一条。"""
    Submission = apps.get_model('submissions', 'Submission')

    groups = {}
    for submission in Submission.objects.all().iterator():
        key = (
            submission.task_assignment_id,
            submission.task_quiz_id,
            submission.attempt_number,
        )
        groups.setdefault(key, []).append(submission)

    for submissions in groups.values():
        if len(submissions) <= 1:
            continue
        submissions.sort(
            key=lambda s: (
                _STATUS_RANK.get(s.status, 0),
                s.obtained_score if s.obtained_score is not None else -1,
                s.submitted_at is not None,
                s.submitted_at or s.created_at,
                s.id,
            ),
            reverse=True,
        )
        for duplicate in submissions[1:]:
            duplicate.delete()


def renumber_attempt_numbers(apps, schema_editor):
    """去重后按组把 attempt_number 压成 1..n，避免留下 1、3 空洞。"""
    Submission = apps.get_model('submissions', 'Submission')

    groups = {}
    for submission in Submission.objects.all().iterator():
        key = (submission.task_assignment_id, submission.task_quiz_id)
        groups.setdefault(key, []).append(submission)

    for submissions in groups.values():
        submissions.sort(key=lambda s: (s.attempt_number, s.created_at, s.id))
        if all(s.attempt_number == index for index, s in enumerate(submissions, start=1)):
            continue
        # 两阶段改号，避免唯一约束（若已存在）下的中间冲突
        for offset, submission in enumerate(submissions):
            submission.attempt_number = _TEMP_ATTEMPT_BASE + offset
            submission.save(update_fields=['attempt_number'])
        for index, submission in enumerate(submissions, start=1):
            submission.attempt_number = index
            submission.save(update_fields=['attempt_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(backfill_or_delete_null_task_quiz, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='submission',
            name='task_quiz',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='submissions',
                to='tasks.taskquiz',
                verbose_name='任务试卷',
            ),
        ),
        migrations.RunPython(delete_duplicate_submissions, migrations.RunPython.noop),
        migrations.RunPython(renumber_attempt_numbers, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(
                fields=('task_assignment', 'task_quiz', 'attempt_number'),
                name='uniq_submission_assignment_task_quiz_attempt',
            ),
        ),
    ]
