# Generated by Django 4.2.7 on 2026-04-14 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_remove_legacy_user_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['submission', 'id'], 'verbose_name': '答案记录', 'verbose_name_plural': '答案记录'},
        ),
    ]
