# Generated by Django 4.2.7 on 2026-08-02 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_cleanup_inconsistent_submissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='remaining_seconds',
        ),
    ]
