# Generated by Django 4.2.7 on 2026-01-26 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', '登录系统'), ('logout', '登出系统'), ('password_change', '修改密码'), ('login_failed', '登录失败'), ('role_assigned', '角色分配')], max_length=50, verbose_name='操作')),
                ('description', models.TextField(verbose_name='详情')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], default='success', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_user_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户日志',
                'verbose_name_plural': '用户日志',
                'db_table': 'user_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='user_logs_created_861293_idx'), models.Index(fields=['user', '-created_at'], name='user_logs_user_id_2ade07_idx'), models.Index(fields=['action', '-created_at'], name='user_logs_action_ed5049_idx')],
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('task_management', '任务管理'), ('grading', '评分操作'), ('spot_check', '抽查记录'), ('data_export', '数据导出')], max_length=50, verbose_name='操作类型')),
                ('action', models.CharField(max_length=100, verbose_name='操作')),
                ('description', models.TextField(verbose_name='操作描述')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('partial', '部分成功')], default='success', max_length=20, verbose_name='状态')),
                ('duration', models.IntegerField(default=0, verbose_name='耗时(毫秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'operation_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='operation_l_created_61eacf_idx'), models.Index(fields=['operation_type', '-created_at'], name='operation_l_operati_0f3aa4_idx'), models.Index(fields=['operator', '-created_at'], name='operation_l_operato_3f48e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('knowledge', '知识文档'), ('quiz', '试卷'), ('question', '题目'), ('assignment', '作业')], max_length=50, verbose_name='内容类型')),
                ('content_id', models.CharField(max_length=100, verbose_name='内容ID')),
                ('content_title', models.CharField(max_length=255, verbose_name='内容标题')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '修改'), ('delete', '删除'), ('publish', '发布')], max_length=50, verbose_name='操作')),
                ('description', models.TextField(verbose_name='详情')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], default='success', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
            ],
            options={
                'verbose_name': '内容日志',
                'verbose_name_plural': '内容日志',
                'db_table': 'content_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='content_log_created_849ccf_idx'), models.Index(fields=['content_type', '-created_at'], name='content_log_content_cd5030_idx'), models.Index(fields=['operator', '-created_at'], name='content_log_operato_202a21_idx')],
            },
        ),
    ]
