# Generated by Django 4.2.7 on 2026-01-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0002_activity_log_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationlog',
            name='operation_type',
            field=models.CharField(choices=[('task_management', '任务管理'), ('grading', '评分操作'), ('spot_check', '抽查记录'), ('data_export', '数据导出'), ('submission', '答题/考试'), ('learning', '学习进度')], max_length=50, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='action',
            field=models.CharField(choices=[('login', '登录系统'), ('logout', '登出系统'), ('password_change', '修改密码'), ('login_failed', '登录失败'), ('role_assigned', '角色分配'), ('mentor_assigned', '分配导师'), ('activate', '启用账号'), ('deactivate', '停用账号'), ('switch_role', '切换角色')], max_length=50, verbose_name='操作'),
        ),
    ]
