# Generated by Codex on 2026-03-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_sync_permission_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermissionoverride',
            name='scope_type',
            field=models.CharField(
                choices=[
                    ('ALL', '全部对象'),
                    ('SELF', '本人数据'),
                    ('MENTEES', '仅名下学员'),
                    ('DEPARTMENT', '仅同部门'),
                    ('EXPLICIT_USERS', '指定用户'),
                ],
                default='ALL',
                max_length=20,
                verbose_name='作用域类型',
            ),
        ),
    ]
