# Generated by Django 4.2.7 on 2026-04-28 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0028_user_permission_override_unique_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermissionoverride',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='userpermissionoverride',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='userscopegroupoverride',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='userscopegroupoverride',
            name='reason',
        ),
    ]
