# Generated by Django 4.2.7 on 2026-07-22 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_seed_system_roles'),
        ('authorization', '0029_drop_override_reason_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoleScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('scope_group_key', models.CharField(db_index=True, max_length=100, verbose_name='范围组键')),
                ('scope_type', models.CharField(choices=[('ALL', '全部对象'), ('OWN', '本人创建'), ('SELF', '本人数据'), ('MENTEES', '仅名下学员'), ('DEPARTMENT', '仅同部门'), ('EXPLICIT_USERS', '指定用户')], max_length=20, verbose_name='范围类型')),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='users.userrole', verbose_name='用户角色')),
            ],
            options={
                'verbose_name': '用户角色范围',
                'verbose_name_plural': '用户角色范围',
                'db_table': 'lms_user_role_scope',
                'ordering': ['user_role_id', 'scope_group_key'],
                'unique_together': {('user_role', 'scope_group_key')},
            },
        ),
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'ordering': ['role__code', 'permission__code'], 'verbose_name': '角色权限', 'verbose_name_plural': '角色权限'},
        ),
        migrations.AddField(
            model_name='permission',
            name='is_configurable',
            field=models.BooleanField(db_index=True, default=True, verbose_name='是否可配置'),
        ),
        migrations.AlterField(
            model_name='userscopegroupoverride',
            name='scope_type',
            field=models.CharField(choices=[('ALL', '全部对象'), ('OWN', '本人创建'), ('SELF', '本人数据'), ('MENTEES', '仅名下学员'), ('DEPARTMENT', '仅同部门'), ('EXPLICIT_USERS', '指定用户')], default='ALL', max_length=20, verbose_name='作用域类型'),
        ),
        migrations.CreateModel(
            name='UserRoleScopeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoped_as_member', to=settings.AUTH_USER_MODEL, verbose_name='目标用户')),
                ('user_role_scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='authorization.userrolescope', verbose_name='用户角色范围')),
            ],
            options={
                'verbose_name': '用户角色范围成员',
                'verbose_name_plural': '用户角色范围成员',
                'db_table': 'lms_user_role_scope_member',
                'ordering': ['user_role_scope_id', 'target_user_id'],
                'unique_together': {('user_role_scope', 'target_user')},
            },
        ),
        migrations.CreateModel(
            name='UserRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_permissions', to='authorization.permission', verbose_name='权限')),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='users.userrole', verbose_name='用户角色')),
            ],
            options={
                'verbose_name': '用户角色权限',
                'verbose_name_plural': '用户角色权限',
                'db_table': 'lms_user_role_permission',
                'ordering': ['user_role_id', 'permission__code'],
                'unique_together': {('user_role', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='RoleScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('scope_group_key', models.CharField(db_index=True, max_length=100, verbose_name='范围组键')),
                ('scope_type', models.CharField(choices=[('ALL', '全部对象'), ('OWN', '本人创建'), ('SELF', '本人数据'), ('MENTEES', '仅名下学员'), ('DEPARTMENT', '仅同部门'), ('EXPLICIT_USERS', '指定用户')], max_length=20, verbose_name='范围类型')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_scopes', to='users.role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '角色范围',
                'verbose_name_plural': '角色范围',
                'db_table': 'lms_role_scope',
                'ordering': ['role__code', 'scope_group_key'],
                'unique_together': {('role', 'scope_group_key')},
            },
        ),
    ]
