# Generated by Django 4.2.7 on 2026-07-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0031_role_permission_absolute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'ordering': ['role__code', 'effect', 'permission__code'], 'verbose_name': '角色权限', 'verbose_name_plural': '角色权限'},
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='effect',
            field=models.CharField(choices=[('ALLOW', '允许'), ('DENY', '拒绝')], db_index=True, default='ALLOW', max_length=10, verbose_name='效果'),
        ),
    ]
