# Generated by Django 4.2.7 on 2026-07-30 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


AUTH_ROLE_CODES = ('MENTOR', 'DEPT', 'GLOBAL')
CRUD_PREFIXES = ('knowledge', 'question', 'quiz', 'spot_check', 'tag', 'task', 'user')

MENTOR_PERMISSIONS = {
    'grading.view', 'grading.score',
    'question.view', 'question.create', 'question.update', 'question.delete',
    'quiz.view', 'quiz.create', 'quiz.update', 'quiz.delete',
    'spot_check.view', 'spot_check.create', 'spot_check.update', 'spot_check.delete',
    'tag.view', 'tag.create',
    'task.view', 'task.create', 'task.update', 'task.delete',
    'task.assign', 'task.analytics.view',
}
DEPT_PERMISSIONS = MENTOR_PERMISSIONS | {
    'knowledge.view', 'knowledge.create', 'knowledge.update', 'knowledge.delete',
    'tag.update', 'tag.delete',
}
GLOBAL_PERMISSIONS = {
    'knowledge.view', 'knowledge.create', 'knowledge.update', 'knowledge.delete',
    'question.view', 'question.create', 'question.update', 'question.delete',
    'quiz.view', 'quiz.create', 'quiz.update', 'quiz.delete',
    'tag.view', 'tag.create', 'tag.update', 'tag.delete',
    'task.view', 'task.create', 'task.update', 'task.delete',
    'task.assign',
    'user.avatar.update', 'user.view', 'user.create', 'user.update', 'user.delete',
    'user.activate', 'user.role.assign', 'user.permission.view', 'user.permission.update',
}
ROLE_PERMISSIONS = {
    'MENTOR': MENTOR_PERMISSIONS,
    'DEPT': DEPT_PERMISSIONS,
    'GLOBAL': GLOBAL_PERMISSIONS,
}


def _implication_map(permission_codes):
    mapping = {
        'grading.view': {'task.view'},
        'grading.score': {'grading.view'},
        'spot_check.create': {'spot_check.view'},
        'task.assign': {'task.view'},
        'task.analytics.view': {'task.view'},
        'user.role.assign': {'user.view'},
        'user.permission.view': {'user.view'},
        'user.permission.update': {'user.permission.view'},
    }
    for prefix in CRUD_PREFIXES:
        view_code = f'{prefix}.view'
        if view_code not in permission_codes:
            continue
        for action in ('create', 'update', 'delete'):
            code = f'{prefix}.{action}'
            if code in permission_codes:
                mapping.setdefault(code, set()).add(view_code)
    return mapping


def _expand(codes, implications):
    expanded = set()
    pending = list(codes)
    while pending:
        code = pending.pop()
        if code in expanded:
            continue
        expanded.add(code)
        pending.extend(implications.get(code, ()))
    return expanded


def materialize_user_permissions(apps, schema_editor):
    Permission = apps.get_model('authorization', 'Permission')
    UserPermission = apps.get_model('authorization', 'UserPermission')
    UserPermissionOverride = apps.get_model('authorization', 'UserPermissionOverride')
    UserRole = apps.get_model('users', 'UserRole')

    permission_ids = dict(
        Permission.objects.filter(is_active=True).values_list('code', 'id')
    )
    implications = _implication_map(set(permission_ids))
    roles_by_user = {}
    for user_id, role_code in UserRole.objects.filter(
        role__code__in=AUTH_ROLE_CODES,
        user__is_superuser=False,
    ).values_list('user_id', 'role__code'):
        if user_id in roles_by_user:
            raise RuntimeError(f'用户 {user_id} 同时拥有多个管理角色')
        roles_by_user[user_id] = role_code

    override_rows = UserPermissionOverride.objects.filter(
        user_id__in=roles_by_user,
        permission__code__in=permission_ids,
    ).values_list('user_id', 'applies_to_role', 'permission__code', 'effect')
    overrides = {}
    for user_id, applies_to_role, code, effect in override_rows:
        role_code = roles_by_user[user_id]
        if applies_to_role not in ('', role_code):
            continue
        overrides.setdefault((user_id, code), set()).add(effect)

    rows = []
    all_codes = set(permission_ids)
    for user_id, role_code in roles_by_user.items():
        role_grants = _expand(ROLE_PERMISSIONS[role_code], implications)
        allow_codes = {
            code
            for (override_user_id, code), effects in overrides.items()
            if override_user_id == user_id and 'ALLOW' in effects and 'DENY' not in effects
        }
        allow_grants = _expand(allow_codes, implications)
        for code in all_codes:
            effects = overrides.get((user_id, code), set())
            if 'DENY' in effects:
                continue
            if code in role_grants or code in allow_grants:
                rows.append(UserPermission(
                    user_id=user_id,
                    permission_id=permission_ids[code],
                ))
    UserPermission.objects.bulk_create(rows, batch_size=1000)


def clear_materialized_permissions(apps, schema_editor):
    apps.get_model('authorization', 'UserPermission').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authorization', '0032_alter_rolepermission_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users', to='authorization.permission', verbose_name='权限')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorization_permissions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户权限',
                'verbose_name_plural': '用户权限',
                'db_table': 'lms_user_permission',
                'ordering': ['user_id', 'permission__code'],
            },
        ),
        migrations.RunPython(
            materialize_user_permissions,
            clear_materialized_permissions,
        ),
        migrations.RemoveField(
            model_name='userpermissionoverride',
            name='granted_by',
        ),
        migrations.RemoveField(
            model_name='userpermissionoverride',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='userpermissionoverride',
            name='user',
        ),
        migrations.DeleteModel(
            name='RolePermission',
        ),
        migrations.DeleteModel(
            name='UserPermissionOverride',
        ),
        migrations.AddConstraint(
            model_name='userpermission',
            constraint=models.UniqueConstraint(fields=('user', 'permission'), name='uniq_user_permission'),
        ),
    ]
