# Generated by Django 4.2.7 on 2026-08-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0033_userpermission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='is_active',
        ),
    ]
