# Generated by Django 4.2.7 on 2026-01-03 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0001_initial'),
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('title', models.CharField(max_length=200, verbose_name='任务标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='任务描述')),
                ('deadline', models.DateTimeField(verbose_name='截止时间')),
                ('is_closed', models.BooleanField(default=False, verbose_name='是否已结束')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'db_table': 'lms_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('resource_uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='试卷资源ID')),
                ('version_number', models.PositiveIntegerField(default=1, verbose_name='试卷版本号')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='顺序')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quiz_tasks', to='quizzes.quiz', verbose_name='试卷')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_quizzes', to='tasks.task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '任务试卷关联',
                'verbose_name_plural': '任务试卷关联',
                'db_table': 'lms_task_quiz',
                'ordering': ['task', 'order'],
                'unique_together': {('task', 'quiz')},
            },
        ),
        migrations.CreateModel(
            name='TaskKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('resource_uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='知识资源ID')),
                ('version_number', models.PositiveIntegerField(default=1, verbose_name='知识版本号')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='顺序')),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_tasks', to='knowledge.knowledge', verbose_name='知识文档')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_knowledge', to='tasks.task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '任务知识关联',
                'verbose_name_plural': '任务知识关联',
                'db_table': 'lms_task_knowledge',
                'ordering': ['task', 'order'],
                'unique_together': {('task', 'knowledge')},
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('IN_PROGRESS', '进行中'), ('COMPLETED', '已完成'), ('OVERDUE', '已逾期')], default='IN_PROGRESS', max_length=20, verbose_name='状态')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='成绩')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_assignments', to=settings.AUTH_USER_MODEL, verbose_name='学员')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tasks.task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '任务分配',
                'verbose_name_plural': '任务分配',
                'db_table': 'lms_task_assignment',
                'ordering': ['task', '-created_at'],
                'unique_together': {('task', 'assignee')},
            },
        ),
        migrations.AddField(
            model_name='task',
            name='knowledge_items',
            field=models.ManyToManyField(related_name='tasks', through='tasks.TaskKnowledge', to='knowledge.knowledge', verbose_name='关联知识'),
        ),
        migrations.AddField(
            model_name='task',
            name='quizzes',
            field=models.ManyToManyField(related_name='tasks', through='tasks.TaskQuiz', to='quizzes.quiz', verbose_name='关联试卷'),
        ),
        migrations.CreateModel(
            name='KnowledgeLearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_progress', to='tasks.taskassignment', verbose_name='任务分配')),
                ('task_knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to='tasks.taskknowledge', verbose_name='任务知识')),
            ],
            options={
                'verbose_name': '知识学习进度',
                'verbose_name_plural': '知识学习进度',
                'db_table': 'lms_knowledge_learning_progress',
                'ordering': ['assignment', 'task_knowledge__order'],
                'unique_together': {('assignment', 'task_knowledge')},
            },
        ),
    ]
