# Generated by Django 4.2.7 on 2026-01-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskknowledge',
            name='resource_uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='知识资源ID'),
        ),
        migrations.AlterField(
            model_name='taskknowledge',
            name='version_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='知识版本号'),
        ),
        migrations.AlterField(
            model_name='taskquiz',
            name='resource_uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='试卷资源ID'),
        ),
        migrations.AlterField(
            model_name='taskquiz',
            name='version_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='试卷版本号'),
        ),
    ]
