# Generated by Django 4.2.7 on 2026-04-27 06:18

from django.db import migrations, models


def initialize_started_at(apps, schema_editor):
    KnowledgeLearningProgress = apps.get_model('tasks', 'KnowledgeLearningProgress')
    KnowledgeLearningProgress.objects.filter(
        is_completed=True,
        completed_at__isnull=False,
    ).update(started_at=models.F('completed_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgelearningprogress',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始学习时间'),
        ),
        migrations.RunPython(initialize_started_at, migrations.RunPython.noop),
    ]
