# Generated by Django 4.2.7 on 2025-12-21 16:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_resource_snapshots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskknowledge',
            name='resource_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='知识资源ID'),
        ),
        migrations.AlterField(
            model_name='taskquiz',
            name='resource_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='试卷资源ID'),
        ),
    ]
