# Generated by Django 4.2.7 on 2025-12-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_taskknowledge_resource_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='task',
            name='pass_score',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_type',
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', '进行中'), ('COMPLETED', '已完成'), ('OVERDUE', '已逾期')], default='IN_PROGRESS', max_length=20, verbose_name='状态'),
        ),
    ]
