# Generated by Django 4.2.7 on 2026-08-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('tasks', '0004_task_auth_permissions')]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_role',
            field=models.CharField(
                choices=[
                    ('ADMIN', '管理员'),
                    ('MENTOR', '导师'),
                    ('DEPT_MANAGER', '室经理'),
                    ('STUDENT', '学员'),
                ],
                db_index=True,
                default='ADMIN',
                max_length=20,
                verbose_name='创建时角色',
            ),
        ),
    ]
