# Generated by Django 4.2.7 on 2026-04-16 09:05

from django.db import migrations, models
import django.db.models.deletion


def ensure_task_source_columns(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SHOW COLUMNS FROM lms_task_knowledge LIKE 'source_knowledge_id'")
        has_source_knowledge = bool(cursor.fetchone())
        if not has_source_knowledge:
            cursor.execute(
                """
                ALTER TABLE lms_task_knowledge
                ADD COLUMN source_knowledge_id bigint NULL,
                ADD INDEX lms_task_knowledge_source_knowledge_id_cf48ad9a_fk_lms_knowl (source_knowledge_id),
                ADD CONSTRAINT lms_task_knowledge_source_knowledge_id_cf48ad9a_fk_lms_knowl
                FOREIGN KEY (source_knowledge_id) REFERENCES lms_knowledge (id)
                """
            )

        cursor.execute("SHOW COLUMNS FROM lms_task_quiz LIKE 'source_quiz_id'")
        has_source_quiz = bool(cursor.fetchone())
        if not has_source_quiz:
            cursor.execute(
                """
                ALTER TABLE lms_task_quiz
                ADD COLUMN source_quiz_id bigint NULL,
                ADD INDEX lms_task_quiz_source_quiz_id_e6bc5ad4_fk_lms_quiz_id (source_quiz_id),
                ADD CONSTRAINT lms_task_quiz_source_quiz_id_e6bc5ad4_fk_lms_quiz_id
                FOREIGN KEY (source_quiz_id) REFERENCES lms_quiz (id)
                """
            )


def remap_task_resources_to_revisions(apps, schema_editor):
    KnowledgeRevision = apps.get_model('knowledge', 'KnowledgeRevision')
    QuizRevision = apps.get_model('quizzes', 'QuizRevision')
    TaskKnowledge = apps.get_model('tasks', 'TaskKnowledge')
    TaskQuiz = apps.get_model('tasks', 'TaskQuiz')

    knowledge_revision_map = {
        revision.source_knowledge_id: revision.id
        for revision in KnowledgeRevision.objects.only('id', 'source_knowledge_id')
    }
    with schema_editor.connection.cursor() as cursor:
        cursor.execute('SET FOREIGN_KEY_CHECKS = 0')
    try:
        for relation in TaskKnowledge.objects.all().iterator():
            relation.source_knowledge_id = relation.knowledge_id
            relation.knowledge_id = knowledge_revision_map.get(relation.knowledge_id)
            relation.save(update_fields=['source_knowledge_id', 'knowledge_id'])

        quiz_revision_map = {
            revision.source_quiz_id: revision.id
            for revision in QuizRevision.objects.only('id', 'source_quiz_id')
        }
        for relation in TaskQuiz.objects.all().iterator():
            relation.source_quiz_id = relation.quiz_id
            relation.quiz_id = quiz_revision_map.get(relation.quiz_id)
            relation.save(update_fields=['source_quiz_id', 'quiz_id'])
    finally:
        with schema_editor.connection.cursor() as cursor:
            cursor.execute('SET FOREIGN_KEY_CHECKS = 1')


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_quizquestionoption_quizrevision_quizrevisionquestion_and_more'),
        ('knowledge', '0002_knowledgerevision_and_more'),
        ('tasks', '0006_remove_task_closed_fields'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunPython(ensure_task_source_columns, noop_reverse)],
            state_operations=[
                migrations.AddField(
                    model_name='taskknowledge',
                    name='source_knowledge',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_bindings', to='knowledge.knowledge', verbose_name='来源知识'),
                ),
                migrations.AddField(
                    model_name='taskquiz',
                    name='source_quiz',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_bindings', to='quizzes.quiz', verbose_name='来源试卷'),
                ),
            ],
        ),
        migrations.RunPython(remap_task_resources_to_revisions, noop_reverse),
        migrations.AlterField(
            model_name='task',
            name='knowledge_items',
            field=models.ManyToManyField(related_name='tasks', through='tasks.TaskKnowledge', to='knowledge.knowledgerevision', verbose_name='关联知识快照'),
        ),
        migrations.AlterField(
            model_name='task',
            name='quizzes',
            field=models.ManyToManyField(related_name='tasks', through='tasks.TaskQuiz', to='quizzes.quizrevision', verbose_name='关联试卷快照'),
        ),
        migrations.AlterField(
            model_name='taskknowledge',
            name='knowledge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_tasks', to='knowledge.knowledgerevision', verbose_name='知识快照'),
        ),
        migrations.AlterField(
            model_name='taskquiz',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quiz_tasks', to='quizzes.quizrevision', verbose_name='试卷快照'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='knowledgelearningprogress',
                    unique_together=set(),
                ),
                migrations.AlterUniqueTogether(
                    name='taskassignment',
                    unique_together=set(),
                ),
                migrations.AlterUniqueTogether(
                    name='taskknowledge',
                    unique_together=set(),
                ),
                migrations.AlterUniqueTogether(
                    name='taskquiz',
                    unique_together=set(),
                ),
                migrations.AddConstraint(
                    model_name='knowledgelearningprogress',
                    constraint=models.UniqueConstraint(fields=('assignment', 'task_knowledge'), name='uniq_assignment_task_knowledge'),
                ),
                migrations.AddConstraint(
                    model_name='taskassignment',
                    constraint=models.UniqueConstraint(fields=('task', 'assignee'), name='uniq_task_assignment_assignee'),
                ),
                migrations.AddConstraint(
                    model_name='taskknowledge',
                    constraint=models.UniqueConstraint(fields=('task', 'order'), name='uniq_task_knowledge_order'),
                ),
                migrations.AddConstraint(
                    model_name='taskquiz',
                    constraint=models.UniqueConstraint(fields=('task', 'order'), name='uniq_task_quiz_order'),
                ),
            ],
        ),
    ]
