# Generated by Django 4.2.7 on 2026-01-03 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('title', models.CharField(max_length=200, verbose_name='试卷名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='试卷描述')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PUBLISHED', '已发布')], default='PUBLISHED', max_length=20, verbose_name='发布状态')),
                ('resource_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='资源标识')),
                ('version_number', models.PositiveIntegerField(default=1, verbose_name='版本号')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('is_current', models.BooleanField(default=True, verbose_name='是否当前版本')),
                ('quiz_type', models.CharField(choices=[('PRACTICE', '练习'), ('EXAM', '考试')], default='PRACTICE', max_length=20, verbose_name='试卷类型')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='考试时长(分钟)')),
                ('pass_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='及格分数')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
                'db_table': 'lms_quiz',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='顺序')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_quizzes', to='questions.question', verbose_name='题目')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='quizzes.quiz', verbose_name='试卷')),
            ],
            options={
                'verbose_name': '试卷题目',
                'verbose_name_plural': '试卷题目',
                'db_table': 'lms_quiz_question',
                'ordering': ['quiz', 'order'],
                'unique_together': {('quiz', 'question')},
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(related_name='quizzes', through='quizzes.QuizQuestion', to='questions.question', verbose_name='题目'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='source_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_versions', to='quizzes.quiz', verbose_name='来源版本'),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.UniqueConstraint(fields=('resource_uuid', 'version_number'), name='uniq_quiz_resource_version'),
        ),
    ]
