# Generated by Django 4.2.7 on 2026-04-16 09:05

import hashlib
import json

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def bootstrap_quiz_snapshots(apps, schema_editor):
    Quiz = apps.get_model('quizzes', 'Quiz')
    QuizQuestion = apps.get_model('quizzes', 'QuizQuestion')
    QuizQuestionOption = apps.get_model('quizzes', 'QuizQuestionOption')
    QuizRevision = apps.get_model('quizzes', 'QuizRevision')
    QuizRevisionQuestion = apps.get_model('quizzes', 'QuizRevisionQuestion')
    QuizRevisionQuestionOption = apps.get_model('quizzes', 'QuizRevisionQuestionOption')
    QuestionOption = apps.get_model('questions', 'QuestionOption')

    for relation in QuizQuestion.objects.select_related('question').all().iterator():
        source_question = relation.question
        if source_question is None:
            continue
        relation.content = source_question.content
        relation.question_type = source_question.question_type
        relation.reference_answer = source_question.reference_answer
        relation.explanation = source_question.explanation
        relation.space_tag_name = source_question.space_tag.name if getattr(source_question, 'space_tag_id', None) else ''
        relation.tags_json = [
            {'id': tag.id, 'name': tag.name, 'tag_type': tag.tag_type}
            for tag in source_question.tags.order_by('id')
        ]
        relation.save(
            update_fields=[
                'content',
                'question_type',
                'reference_answer',
                'explanation',
                'space_tag_name',
                'tags_json',
            ]
        )
        for option in QuestionOption.objects.filter(question_id=source_question.id).order_by('sort_order', 'id'):
            QuizQuestionOption.objects.get_or_create(
                question_id=relation.id,
                sort_order=option.sort_order,
                defaults={
                    'content': option.content,
                    'is_correct': option.is_correct,
                },
            )

    for quiz in Quiz.objects.all().iterator():
        question_payloads = []
        relations = QuizQuestion.objects.filter(quiz_id=quiz.id).order_by('order', 'id')
        for relation in relations:
            options = list(
                QuizQuestionOption.objects.filter(question_id=relation.id)
                .order_by('sort_order', 'id')
                .values('sort_order', 'content', 'is_correct')
            )
            question_payloads.append(
                {
                    'source_question_id': relation.question_id,
                    'content': relation.content,
                    'question_type': relation.question_type,
                    'reference_answer': relation.reference_answer,
                    'explanation': relation.explanation,
                    'score': str(relation.score),
                    'order': relation.order,
                    'space_tag_name': relation.space_tag_name,
                    'tags_json': relation.tags_json,
                    'options': options,
                }
            )
        structure_hash = hashlib.sha256(
            json.dumps(
                {
                    'title': quiz.title,
                    'quiz_type': quiz.quiz_type,
                    'duration': quiz.duration,
                    'pass_score': str(quiz.pass_score) if quiz.pass_score is not None else None,
                    'questions': question_payloads,
                },
                sort_keys=True,
                ensure_ascii=False,
                default=str,
            ).encode('utf-8')
        ).hexdigest()
        revision, _ = QuizRevision.objects.get_or_create(
            source_quiz_id=quiz.id,
            revision_number=quiz.version_number,
            defaults={
                'title': quiz.title,
                'quiz_type': quiz.quiz_type,
                'duration': quiz.duration,
                'pass_score': quiz.pass_score,
                'structure_hash': structure_hash,
                'created_by_id': quiz.created_by_id,
            },
        )
        if revision.quiz_questions.exists():
            continue
        for question_payload in question_payloads:
            revision_question = QuizRevisionQuestion.objects.create(
                quiz_id=revision.id,
                question_id=question_payload['source_question_id'],
                content=question_payload['content'],
                question_type=question_payload['question_type'],
                reference_answer=question_payload['reference_answer'],
                explanation=question_payload['explanation'],
                score=question_payload['score'],
                order=question_payload['order'],
                space_tag_name=question_payload['space_tag_name'],
                tags_json=question_payload['tags_json'],
            )
            QuizRevisionQuestionOption.objects.bulk_create(
                [
                    QuizRevisionQuestionOption(
                        question_id=revision_question.id,
                        sort_order=option['sort_order'],
                        content=option['content'],
                        is_correct=option['is_correct'],
                    )
                    for option in question_payload['options']
                ]
            )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_remove_question_uniq_question_resource_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0003_quiz_deleted_at_quiz_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sort_order', models.PositiveIntegerField(default=1, verbose_name='排序')),
                ('content', models.TextField(verbose_name='选项内容')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正确答案')),
            ],
            options={
                'verbose_name': '试卷题目选项',
                'verbose_name_plural': '试卷题目选项',
                'db_table': 'lms_quiz_question_option',
                'ordering': ['question_id', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=200, verbose_name='试卷名称')),
                ('quiz_type', models.CharField(choices=[('PRACTICE', '测验'), ('EXAM', '考试')], default='PRACTICE', max_length=20, verbose_name='试卷类型')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='考试时长(分钟)')),
                ('pass_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='及格分数')),
                ('revision_number', models.PositiveIntegerField(default=1, verbose_name='快照版本号')),
                ('structure_hash', models.CharField(db_index=True, max_length=64, verbose_name='结构哈希')),
            ],
            options={
                'verbose_name': '试卷快照',
                'verbose_name_plural': '试卷快照',
                'db_table': 'lms_quiz_revision',
                'ordering': ['-created_at', '-revision_number'],
            },
        ),
        migrations.CreateModel(
            name='QuizRevisionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.TextField(default='', verbose_name='题目内容')),
                ('question_type', models.CharField(choices=[('SINGLE_CHOICE', '单选题'), ('MULTIPLE_CHOICE', '多选题'), ('TRUE_FALSE', '判断题'), ('SHORT_ANSWER', '简答题')], default='SHORT_ANSWER', max_length=20, verbose_name='题目类型')),
                ('reference_answer', models.TextField(blank=True, default='', verbose_name='参考答案')),
                ('explanation', models.TextField(blank=True, default='', verbose_name='解析')),
                ('score', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='分值')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='顺序')),
                ('space_tag_name', models.CharField(blank=True, default='', max_length=100, verbose_name='space 名称')),
                ('tags_json', models.JSONField(blank=True, default=list, verbose_name='标签快照')),
            ],
            options={
                'verbose_name': '试卷快照题目',
                'verbose_name_plural': '试卷快照题目',
                'db_table': 'lms_quiz_revision_question',
                'ordering': ['quiz_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizRevisionQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sort_order', models.PositiveIntegerField(default=1, verbose_name='排序')),
                ('content', models.TextField(verbose_name='选项内容')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正确答案')),
            ],
            options={
                'verbose_name': '试卷快照题目选项',
                'verbose_name_plural': '试卷快照题目选项',
                'db_table': 'lms_quiz_revision_question_option',
                'ordering': ['question_id', 'sort_order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'ordering': ['quiz_id', 'order', 'id'], 'verbose_name': '试卷题目', 'verbose_name_plural': '试卷题目'},
        ),
        migrations.AlterUniqueTogether(
            name='quizquestion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='content',
            field=models.TextField(default='', verbose_name='题目内容'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='explanation',
            field=models.TextField(blank=True, default='', verbose_name='解析'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('SINGLE_CHOICE', '单选题'), ('MULTIPLE_CHOICE', '多选题'), ('TRUE_FALSE', '判断题'), ('SHORT_ANSWER', '简答题')], default='SHORT_ANSWER', max_length=20, verbose_name='题目类型'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='reference_answer',
            field=models.TextField(blank=True, default='', verbose_name='参考答案'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='space_tag_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='space 名称'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='tags_json',
            field=models.JSONField(blank=True, default=list, verbose_name='标签快照'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_copies', to='questions.question', verbose_name='来源题库题'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='score',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='分值'),
        ),
        migrations.AddConstraint(
            model_name='quizquestion',
            constraint=models.UniqueConstraint(fields=('quiz', 'order'), name='uniq_quiz_question_order'),
        ),
        migrations.AddField(
            model_name='quizrevisionquestionoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_options', to='quizzes.quizrevisionquestion', verbose_name='试卷快照题目'),
        ),
        migrations.AddField(
            model_name='quizrevisionquestion',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_revision_entries', to='questions.question', verbose_name='来源题库题'),
        ),
        migrations.AddField(
            model_name='quizrevisionquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='quizzes.quizrevision', verbose_name='试卷快照'),
        ),
        migrations.AddField(
            model_name='quizrevision',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='quizrevision',
            name='source_quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='quizzes.quiz', verbose_name='来源试卷'),
        ),
        migrations.AddField(
            model_name='quizquestionoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_options', to='quizzes.quizquestion', verbose_name='试卷题目'),
        ),
        migrations.AddConstraint(
            model_name='quizrevisionquestionoption',
            constraint=models.UniqueConstraint(fields=('question', 'sort_order'), name='uniq_quiz_revision_question_option_order'),
        ),
        migrations.AddConstraint(
            model_name='quizrevisionquestion',
            constraint=models.UniqueConstraint(fields=('quiz', 'order'), name='uniq_quiz_revision_question_order'),
        ),
        migrations.AddConstraint(
            model_name='quizrevision',
            constraint=models.UniqueConstraint(fields=('source_quiz', 'revision_number'), name='uniq_quiz_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='quizquestionoption',
            constraint=models.UniqueConstraint(fields=('question', 'sort_order'), name='uniq_quiz_question_option_order'),
        ),
        migrations.RunPython(bootstrap_quiz_snapshots, noop_reverse),
    ]
