# Generated by Django 4.2.7 on 2026-01-17 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_add_current_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='source_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_versions', to='quizzes.quiz', verbose_name='来源版本'),
        ),
    ]
