# Generated by Django 4.2.7 on 2026-01-19 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0005_remove_quiz_source_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_updated', to=settings.AUTH_USER_MODEL, verbose_name='最后更新者'),
        ),
    ]
