# Generated by Django 4.2.7 on 2026-02-20 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_add_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='description',
        ),
    ]
