export const USER_PERMISSION_VIEW_PERMISSION = 'user.permission.view';
export const USER_PERMISSION_UPDATE_PERMISSION = 'user.permission.update';
export const USER_ROLE_ASSIGN_PERMISSION = 'user.role.assign';

export const USER_PERMISSION_ACCESS_PERMISSIONS = [
  USER_PERMISSION_VIEW_PERMISSION,
  USER_PERMISSION_UPDATE_PERMISSION,
];

/** 授权工作台：用户角色分配 + 用户权限配置 */
export const AUTHORIZATION_WORKBENCH_ACCESS_PERMISSIONS = [
  ...USER_PERMISSION_ACCESS_PERMISSIONS,
  USER_ROLE_ASSIGN_PERMISSION,
];
