# Generated by Django 4.2.7 on 2026-04-20 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spot_checks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotcheck',
            name='checker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spot_checks_created', to=settings.AUTH_USER_MODEL, verbose_name='抽查人'),
        ),
        migrations.AddField(
            model_name='spotcheck',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spot_checks_received', to=settings.AUTH_USER_MODEL, verbose_name='被抽查学员'),
        ),
    ]
