# Generated by Django 4.2.7 on 2025-12-12 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='操作类型')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='类型代码')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '操作类型',
                'verbose_name_plural': '操作类型',
                'db_table': 'operation_types',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='分类代码')),
                ('level', models.IntegerField(choices=[(1, '条线'), (2, '系统')], verbose_name='层级')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='knowledge.knowledgecategory', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '知识分类',
                'verbose_name_plural': '知识分类',
                'db_table': 'knowledge_categories',
                'ordering': ['level', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='摘要')),
                ('cover_image', models.CharField(blank=True, max_length=500, null=True, verbose_name='封面图片URL')),
                ('attachment_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='附带链接')),
                ('content_scenario', models.TextField(verbose_name='故障场景')),
                ('content_trigger', models.TextField(verbose_name='触发流程')),
                ('content_solution', models.TextField(verbose_name='解决方案')),
                ('content_verification', models.TextField(verbose_name='验证方案')),
                ('content_recovery', models.TextField(verbose_name='恢复方案')),
                ('emergency_platform', models.CharField(blank=True, max_length=100, null=True, verbose_name='应急平台')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PUBLISHED', '已发布'), ('ARCHIVED', '已归档')], default='DRAFT', max_length=20, verbose_name='状态')),
                ('view_count', models.IntegerField(default=0, verbose_name='阅读次数')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_knowledge', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('creator_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_knowledge', to='users.department', verbose_name='创建人所属团队')),
                ('deliverer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_knowledge', to=settings.AUTH_USER_MODEL, verbose_name='场景交付人')),
                ('executors', models.ManyToManyField(blank=True, related_name='executable_knowledge', to=settings.AUTH_USER_MODEL, verbose_name='可执行人')),
                ('line', models.ForeignKey(limit_choices_to={'level': 1}, on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_line', to='knowledge.knowledgecategory', verbose_name='所属条线')),
                ('modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_knowledge', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
                ('operation_types', models.ManyToManyField(related_name='knowledge_docs', to='knowledge.operationtype', verbose_name='操作类型')),
                ('system', models.ForeignKey(limit_choices_to={'level': 2}, on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_system', to='knowledge.knowledgecategory', verbose_name='所属系统')),
            ],
            options={
                'verbose_name': '应急操作手册',
                'verbose_name_plural': '应急操作手册',
                'db_table': 'knowledge',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['line', 'system'], name='knowledge_line_id_e4dce3_idx'), models.Index(fields=['status', 'is_deleted'], name='knowledge_status_9103f0_idx'), models.Index(fields=['-created_at'], name='knowledge_created_e325ee_idx')],
            },
        ),
    ]
