# Generated by Django 4.2.7 on 2025-12-15 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('knowledge_type', models.CharField(choices=[('EMERGENCY', '应急类'), ('OTHER', '其他类型')], max_length=20, verbose_name='知识类型')),
                ('summary', models.TextField(blank=True, default='', verbose_name='摘要')),
                ('content', models.TextField(blank=True, default='', verbose_name='正文内容')),
                ('fault_scenario', models.TextField(blank=True, default='', verbose_name='故障场景')),
                ('trigger_process', models.TextField(blank=True, default='', verbose_name='触发流程')),
                ('solution', models.TextField(blank=True, default='', verbose_name='解决方案')),
                ('verification_plan', models.TextField(blank=True, default='', verbose_name='验证方案')),
                ('recovery_plan', models.TextField(blank=True, default='', verbose_name='恢复方案')),
                ('operation_tags', models.JSONField(blank=True, default=list, verbose_name='操作类型标签')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='阅读次数')),
            ],
            options={
                'verbose_name': '知识文档',
                'verbose_name_plural': '知识文档',
                'db_table': 'lms_knowledge',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='分类代码')),
                ('description', models.TextField(blank=True, default='', verbose_name='分类描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序顺序')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='knowledge.knowledgecategory', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '知识分类',
                'verbose_name_plural': '知识分类',
                'db_table': 'lms_knowledge_category',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeCategoryRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否主分类')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_relations', to='knowledge.knowledgecategory', verbose_name='分类')),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_relations', to='knowledge.knowledge', verbose_name='知识文档')),
            ],
            options={
                'verbose_name': '知识分类关联',
                'verbose_name_plural': '知识分类关联',
                'db_table': 'lms_knowledge_category_relation',
                'ordering': ['knowledge', 'category'],
                'unique_together': {('knowledge', 'category')},
            },
        ),
        migrations.AddField(
            model_name='knowledge',
            name='categories',
            field=models.ManyToManyField(related_name='knowledge_items', through='knowledge.KnowledgeCategoryRelation', to='knowledge.knowledgecategory', verbose_name='所属分类'),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_updated', to=settings.AUTH_USER_MODEL, verbose_name='最后更新者'),
        ),
    ]
