# Generated by Django 4.2.7 on 2025-12-19 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='标签名称')),
                ('tag_type', models.CharField(choices=[('LINE', '条线类型'), ('SYSTEM', '系统标签'), ('OPERATION', '操作标签')], max_length=20, verbose_name='标签类型')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序序号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('parent', models.ForeignKey(blank=True, help_text='系统标签可关联条线类型', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='knowledge.tag', verbose_name='父标签')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'lms_tag',
                'ordering': ['tag_type', 'sort_order', 'name'],
                'unique_together': {('name', 'tag_type')},
            },
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('knowledge_type', models.CharField(choices=[('EMERGENCY', '应急类'), ('OTHER', '其他类型')], max_length=20, verbose_name='知识类型')),
                ('fault_scenario', models.TextField(blank=True, default='', verbose_name='故障场景')),
                ('trigger_process', models.TextField(blank=True, default='', verbose_name='触发流程')),
                ('solution', models.TextField(blank=True, default='', verbose_name='解决方案')),
                ('verification_plan', models.TextField(blank=True, default='', verbose_name='验证方案')),
                ('recovery_plan', models.TextField(blank=True, default='', verbose_name='恢复方案')),
                ('content', models.TextField(blank=True, default='', verbose_name='正文内容')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='阅读次数')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('line_type', models.ForeignKey(limit_choices_to={'is_active': True, 'tag_type': 'LINE'}, on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_by_line', to='knowledge.tag', verbose_name='条线类型')),
                ('operation_tags', models.ManyToManyField(blank=True, limit_choices_to={'is_active': True, 'tag_type': 'OPERATION'}, related_name='knowledge_by_operation', to='knowledge.tag', verbose_name='操作标签')),
                ('system_tags', models.ManyToManyField(blank=True, limit_choices_to={'is_active': True, 'tag_type': 'SYSTEM'}, related_name='knowledge_by_system', to='knowledge.tag', verbose_name='系统标签')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_updated', to=settings.AUTH_USER_MODEL, verbose_name='最后更新者')),
            ],
            options={
                'verbose_name': '知识文档',
                'verbose_name_plural': '知识文档',
                'db_table': 'lms_knowledge',
                'ordering': ['-updated_at'],
            },
        ),
    ]
