# Generated by Django 4.2.7 on 2026-04-20 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgerevision',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='knowledgerevision',
            name='source_knowledge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='knowledge.knowledge', verbose_name='来源知识'),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='space_tag',
            field=models.ForeignKey(blank=True, limit_choices_to={'tag_type': 'SPACE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_by_space', to='tags.tag', verbose_name='space'),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='tags',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tag_type': 'TAG'}, related_name='knowledge_items', to='tags.tag', verbose_name='知识标签'),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_updated', to=settings.AUTH_USER_MODEL, verbose_name='最后更新者'),
        ),
        migrations.AddConstraint(
            model_name='knowledgerevision',
            constraint=models.UniqueConstraint(fields=('source_knowledge', 'revision_number'), name='uniq_knowledge_revision_number'),
        ),
    ]
