# Generated by Django migration

from django.db import migrations, models


def set_existing_knowledge_as_published(apps, schema_editor):
    """
    将现有知识文档设置为已发布状态
    """
    Knowledge = apps.get_model('knowledge', 'Knowledge')
    Knowledge.objects.all().update(status='PUBLISHED')


def reverse_set_status(apps, schema_editor):
    """
    反向操作：不需要做任何操作
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_fill_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='status',
            field=models.CharField(
                choices=[('DRAFT', '草稿'), ('PUBLISHED', '已发布')],
                default='DRAFT',
                help_text='草稿状态仅创建者和管理员可见，已发布状态可用于任务分配',
                max_length=20,
                verbose_name='发布状态'
            ),
        ),
        migrations.AddIndex(
            model_name='knowledge',
            index=models.Index(fields=['status', 'is_deleted'], name='lms_knowled_status_is_deleted_idx'),
        ),
        migrations.RunPython(set_existing_knowledge_as_published, reverse_set_status),
    ]


