# Generated by Django 4.2.7 on 2026-01-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_remove_status_field'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='knowledge',
            constraint=models.UniqueConstraint(
                fields=('resource_uuid',),
                condition=models.Q(('is_current', True)),
                name='uniq_knowledge_current'
            ),
        ),
    ]
