# Generated by Django 4.2.7 on 2026-08-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='external_doc_url',
            field=models.URLField(
                blank=True,
                default='',
                help_text='第三方文档查看链接，编辑时追加 mode=edit',
                max_length=500,
                verbose_name='文档链接',
            ),
        ),
        migrations.AddField(
            model_name='knowledgerevision',
            name='external_doc_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='文档链接'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='步骤摘要'),
        ),
        migrations.AlterField(
            model_name='knowledgerevision',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='步骤摘要'),
        ),
    ]
