# Generated by Django migration

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_add_knowledge_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='published_version',
            field=models.ForeignKey(
                blank=True,
                help_text='如果这是草稿，此字段指向对应的已发布版本',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='draft_versions',
                to='knowledge.knowledge',
                verbose_name='已发布版本'
            ),
        ),
    ]


