# Generated by Django 4.2.7 on 2026-01-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_remove_knowledge_source_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='source_url',
            field=models.URLField(blank=True, help_text='在线文档链接（腾讯文档/飞书等）', max_length=500, null=True, verbose_name='原始文档链接'),
        ),
    ]
