# Generated by Django 4.2.7 on 2025-12-21 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0007_versioning_and_snapshots'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledge',
            options={'ordering': ['-created_at'], 'verbose_name': '知识文档', 'verbose_name_plural': '知识文档'},
        ),
        migrations.RemoveIndex(
            model_name='knowledge',
            name='lms_knowled_status_is_deleted_idx',
        ),
        migrations.RenameIndex(
            model_name='resourcelinetype',
            new_name='lms_resourc_content_e5ec4d_idx',
            old_name='lms_resour_content_idx',
        ),
    ]
