# Generated by Django 4.2.7 on 2026-03-30 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_remove_tag_is_active'),
        ('knowledge', '0014_rename_line_tag_to_space_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='space_tag',
            field=models.ForeignKey(blank=True, limit_choices_to={'tag_type': 'SPACE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_by_space', to='tags.tag', verbose_name='space'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='tags',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tag_type': 'TAG'}, related_name='knowledge_items', to='tags.tag', verbose_name='知识标签'),
        ),
    ]
