# Generated by Django 4.2.7 on 2025-12-12 15:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SINGLE', '单选题'), ('MULTIPLE', '多选题'), ('JUDGE', '判断题'), ('ESSAY', '简答题')], max_length=20, verbose_name='题目类型')),
                ('content', models.TextField(verbose_name='题目内容')),
                ('options', models.JSONField(blank=True, help_text='选择题的选项，JSON格式', null=True, verbose_name='选项')),
                ('correct_answer', models.JSONField(help_text='JSON格式存储答案', verbose_name='正确答案')),
                ('analysis', models.TextField(blank=True, null=True, verbose_name='题目解析')),
                ('difficulty', models.IntegerField(default=3, help_text='难度等级：1-5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='难度')),
                ('is_public', models.BooleanField(default=False, help_text='公开题目可被所有人使用', verbose_name='是否公开')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'db_table': 'questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='测验标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='测验描述')),
                ('total_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name='总分')),
                ('pass_score', models.DecimalField(decimal_places=2, default=60.0, max_digits=5, verbose_name='及格分')),
                ('is_public', models.BooleanField(default=False, help_text='公开测验可被所有人使用', verbose_name='是否公开')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quizzes', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '测验',
                'verbose_name_plural': '测验',
                'db_table': 'quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(help_text='题目在测验中的顺序', verbose_name='排序')),
                ('score', models.DecimalField(decimal_places=2, help_text='该题目在此测验中的分值', max_digits=5, verbose_name='分值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='questions.question', verbose_name='题目')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='questions.quiz', verbose_name='测验')),
            ],
            options={
                'verbose_name': '测验题目',
                'verbose_name_plural': '测验题目',
                'db_table': 'quiz_questions',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(related_name='quizzes', through='questions.QuizQuestion', to='questions.question', verbose_name='题目'),
        ),
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['quiz', 'sort_order'], name='quiz_questi_quiz_id_739782_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quizquestion',
            unique_together={('quiz', 'question')},
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['is_public'], name='quizzes_is_publ_764774_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['is_deleted'], name='quizzes_is_dele_ce55af_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['created_by'], name='quizzes_created_02cca3_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['type'], name='questions_type_aca5a9_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty'], name='questions_difficu_8150ad_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_public'], name='questions_is_publ_a62568_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_deleted'], name='questions_is_dele_3c95f1_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['created_by'], name='questions_created_59d8b2_idx'),
        ),
    ]
