# Generated by Django 4.2.7 on 2025-12-15 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('content', models.TextField(verbose_name='题目内容')),
                ('question_type', models.CharField(choices=[('SINGLE_CHOICE', '单选题'), ('MULTIPLE_CHOICE', '多选题'), ('TRUE_FALSE', '判断题'), ('SHORT_ANSWER', '简答题')], max_length=20, verbose_name='题目类型')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='选项')),
                ('answer', models.JSONField(verbose_name='答案')),
                ('explanation', models.TextField(blank=True, default='', verbose_name='解析')),
                ('score', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='分值')),
                ('difficulty', models.CharField(choices=[('EASY', '简单'), ('MEDIUM', '中等'), ('HARD', '困难')], default='MEDIUM', max_length=10, verbose_name='难度等级')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'db_table': 'lms_question',
                'ordering': ['-created_at'],
            },
        ),
    ]
