# Generated by Django 4.2.7 on 2026-04-16 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_quiz_deleted_at_quiz_is_deleted'),
        ('questions', '0003_remove_legacy_question_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_from_quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bank_questions', to='quizzes.quiz', verbose_name='首次沉淀来源试卷'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(default='', verbose_name='题目内容'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SINGLE_CHOICE', '单选题'), ('MULTIPLE_CHOICE', '多选题'), ('TRUE_FALSE', '判断题'), ('SHORT_ANSWER', '简答题')], default='SHORT_ANSWER', max_length=20, verbose_name='题目类型'),
        ),
    ]
