# Generated by Django 4.2.7 on 2026-01-17 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_question_source_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='source_version',
        ),
    ]
