# Generated by Django 4.2.7 on 2026-01-19 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0006_remove_question_source_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_updated', to=settings.AUTH_USER_MODEL, verbose_name='最后更新者'),
        ),
    ]
