# Generated by Django 4.2.7 on 2026-03-30 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_rename_line_to_space'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='is_active',
        ),
    ]
