export const ROLE_PERMISSION_TEMPLATE_VIEW_PERMISSION = 'role_permission_template.view';
export const ROLE_PERMISSION_TEMPLATE_UPDATE_PERMISSION = 'role_permission_template.update';
export const USER_PERMISSION_VIEW_PERMISSION = 'user.permission.view';
export const USER_PERMISSION_UPDATE_PERMISSION = 'user.permission.update';
export const USER_ROLE_ASSIGN_PERMISSION = 'user.role.assign';

export const ROLE_PERMISSION_TEMPLATE_ACCESS_PERMISSIONS = [
  ROLE_PERMISSION_TEMPLATE_VIEW_PERMISSION,
  ROLE_PERMISSION_TEMPLATE_UPDATE_PERMISSION,
];

export const USER_PERMISSION_ACCESS_PERMISSIONS = [
  USER_PERMISSION_VIEW_PERMISSION,
  USER_PERMISSION_UPDATE_PERMISSION,
];

export const AUTHORIZATION_WORKBENCH_ACCESS_PERMISSIONS = [
  ...ROLE_PERMISSION_TEMPLATE_ACCESS_PERMISSIONS,
  ...USER_PERMISSION_ACCESS_PERMISSIONS,
  USER_ROLE_ASSIGN_PERMISSION,
];
