export const USER_PERMISSION_VIEW_PERMISSION = 'users.view_user_permission';
export const USER_PERMISSION_UPDATE_PERMISSION = 'users.change_user_permission';
export const USER_ROLE_ASSIGN_PERMISSION = 'users.assign_user_role';

export const USER_PERMISSION_ACCESS_PERMISSIONS = [
  USER_PERMISSION_VIEW_PERMISSION,
  USER_PERMISSION_UPDATE_PERMISSION,
];

export const AUTHORIZATION_WORKBENCH_ACCESS_PERMISSIONS = [
  ...USER_PERMISSION_ACCESS_PERMISSIONS,
  USER_ROLE_ASSIGN_PERMISSION,
];
