# Generated by Django 4.2.7 on 2025-12-15 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_notification_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='lms_notific_recipie_86441c_idx',
            old_name='lms_notific_recipie_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='lms_notific_recipie_52a011_idx',
            old_name='lms_notific_recipie_d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='lms_notific_notific_888428_idx',
            old_name='lms_notific_notific_g7h8i9_idx',
        ),
    ]
